import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {NodeIO} from '@gltf-transform/core';
import {ALL_EXTENSIONS} from '@gltf-transform/extensions';
import {dedup,prune,meshopt} from '@gltf-transform/functions';
import {MeshoptEncoder,MeshoptDecoder} from 'meshoptimizer';
await MeshoptEncoder.ready;
const io=new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.encoder':MeshoptEncoder,'meshopt.decoder':MeshoptDecoder});
const source='../assets/interchange/departamento-t7.glb';
const document=await io.read(source);
const names=document.getRoot().listNodes().map(n=>n.getName());
await document.transform(dedup({keepUniqueNames:true}),prune({keepLeaves:true,keepExtras:true,keepAttributes:true}),meshopt({encoder:MeshoptEncoder,level:'medium',quantizePosition:16,quantizeNormal:12,quantizeTexcoord:16}));
if(names.join('|')!==document.getRoot().listNodes().map(n=>n.getName()).join('|'))throw new Error('Optimization changed node identities');
const output='public/models/departamento-t7-web.glb';await io.write(output,document);
const manifest=JSON.parse(fs.readFileSync('public/models/manifest.json'));
manifest.model='departamento-t7-web.glb';manifest.interchange_model='departamento-t7.glb';manifest.hashes['departamento-t7-web.glb']=createHash('sha256').update(fs.readFileSync(output)).digest('hex');
fs.writeFileSync('public/models/manifest.json',JSON.stringify(manifest,null,2)+'\n');
const report={revision:manifest.revision,source_bytes:fs.statSync(source).size,web_bytes:fs.statSync(output).size,nodes_preserved:names.length,position_bits:16,normal_bits:12,texture_bits:16,compression:'EXT_meshopt_compression',source_unchanged:true};
fs.mkdirSync('../validation/e09',{recursive:true});fs.writeFileSync('../validation/e09/optimization.json',JSON.stringify(report,null,2)+'\n');console.log(report);
